### ISSUE TITLE
https://validator.w3.org/nu/ is down - error 503

### ISSUE THREAD

**Issue by lklepner** [zrrrzzt/html-validator#162]
This isn't a code related problem.. but having validator.w3.org/nu/ down has me wondering if validation is possible w/o relying on a third-party service.

**Comment by zrrrzzt** [comment]
There are at least 2 ways I can think of.

1. Run your own instance of the validator
You have a `validator` property in the `options` for this module. Point this to your own instance of the validator and even if it still is an external service you would have full control.
The [Nu Html Checker](https://github.com/validator/validator) is open source and I think there is a prebuilt docker available as well

2. Have the validator integrated in this module
In theory it would be possible to use something like WASM and use the generated code as a part of the module. This could be very interesting but I don't have the time to look into it. I'm not sure how much it would add to the size of the package either... but it would give you a completely autonomous module.

**Comment by jfoclpf** [comment]
This would be really a great improvement cause relying on this external service is very unreliable. It would be really great to have a fully autonomous and fully local validator.

**Comment by zrrrzzt** [comment]
After I found this https://www.npmjs.com/package/html-validate module, option 2 is a bit closer :-)
I'm not sure how much work it would require but I'll look into it.

**Comment by zrrrzzt** [comment]
Working on an implementation here: https://github.com/zrrrzzt/html-validator/tree/html-validate
Code is working, documentation is not updated. Will probably release this weekend.

**Comment by jfoclpf** [comment]
I followed your tip and started to make some tests with `html-validate` and contrary to what I expected, my files, which were running perfectly on your W3C validator with no errors nor warnings, suddenly started to have 300 and more errors with `html-validate`. So, regarding your transition just mind that your users might get angry because suddenly the validator is outputting (a lot of new several) errors. 

`html-validate` is very strict and goes beyond W3C rules, for example even on simple things which I find too much, like trailing spaces.

Here an example: this is perfectly ok for W3C

```html
<meta name='author' content="Autocosts Org" />
```

Nonetheless according to `html-validate` that html code that has 3 errors: 
 - the `/` at the end, 
 - the trailing space, and 
 - the `'` quotes for the name. 

Thus it must be this:

```html
<meta name="author" content="Autocosts Org">
```

just to let you know

**Comment by XhmikosR** [comment]
For what is worth, the latest vnu.jar versions are self contained, i.e. no need for the Java runtime. But these builds are not included in the official npm package.

**Comment by jfoclpf** [comment]
@zrrrzzt it seems @XhmikosR is right, maybe it's better to keep the W3C validator cause it's official. I was making further tests and I discovered errors which are triggered by W3C and not by `html-validate`, which is not good, since many SEO rankings are based on the W3C

Particularly I found this

```html
<a class="btn btn-danger cursor_pointer close" data-action="close" data-side="left">
  <span alt="some text"></span>
</a>
```

Whilst `html-validate` was not complaining, W3C refers that the `alt` attribute cannot be there inside `span`

**Comment by zrrrzzt** [comment]
You are doing an excellent job providing examples @jfoclpf :-)

As long as the validator follows the html standards specifications it should not matter if it is developed by w3c or any other. I've opened an issue at the html-validate repo https://gitlab.com/html-validate/html-validate/issues/66 and your first case is because the default setting for html-validate cares about cosmetics as well.

I might need to spend some more time with this problem. I think it is important to get the same errors with a new version given the original errors were correct.

By configuring the right ruleset it should bee possible to get the same result.

Another possible solution would be to offer both validators from the module. Use w3c over the wire or html-validate completely on your own machine.

**Comment by jfoclpf** [comment]
Thanks :)
That's a nice idea of using both W3C and `html-validate` according to the user's preference in some configuration object.

What I would strongly suggest you then, to avoid the test suites to output errors due to the fact that the W3C server is down (which is very frustrating because the end user which is simply making a commit may think he has done something wrong), is to [ping](https://www.npmjs.com/package/ping) the W3C server before each request.
I mean before each request because I had some tests in which the first 20 files were tested OK, but the W3C server went down after the 21st request.

If the user selects W3C and its server is down, then you can use `html-validate` as backup. You may have 3 options for `validator` property: 

 - "W3C", // uses only the official W3C validator (online); if server is down, throws "server down" error
 - "W3C-html-validate", // uses the official W3C validator (online); if server down uses local offline html-validate, 
  - "html-validate", // only uses the local offline html-validate

What do you think?

I think for now it would be very hard to mimic the W3C validator just by fine-tuning the html-validate rules.

**Comment by zrrrzzt** [comment]
I've been informed of another difference between the validators. html-validate follows the WHATWG standard and according to [this blog-post from W3C](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/) that is a good idea.

I don't think pinging the server will resolve all your problems. The server can go down between the ping and validation. If you need a more stable environment you could run a local version of the W3C validator yourself and just pass the url to html-validator.

The interface for a version supporting both would probably be validator:W3C (default) and WHATWG (optional, will use html-validate without the cosmetic rules)

**Comment by jfoclpf** [comment]
Ok, I see. Can that local version of the W3C be installed without root permissions? The test suite must be easily transposed to other machines, for example via `npm install --only=dev` or `or git clone`. Instead of ping why not `try` and `catch` directives? I think you use the `request` package for accessing the W3C server, I suppose `request` throws an error when the server is down.  Just my five cents :)

**Comment by zrrrzzt** [comment]
Request got deprecated this week so I'll probably change that to Axios.

The question is what do to with the error :-) As it is now I leave it to the module on the next level to decide. You can either crash or you can implement functionality for saying something like "could not validate this right now, move on"

**Comment by jfoclpf** [comment]
I was checking the thread on deprecation of `request` and it is really a
bold move since more than 41k packages depend on `request`. I was checking
also `axios` and it seems a good replacement with millions of downloads per
month. I would also need to do the same on my packages. Nonetheless the
same main developer of `request` is working on `bent` because he says the
paradigm in JS has changed.

Regarding the error issue I fully agree with you, we should let the higher
level decide what to do when the W3C server is down.

**Comment by jfoclpf** [comment]
Hi @zrrrzzt just then a final question :) 
My code is something like this

Which specific error is thrown when the server is down?
How to catch it?

```js
const validator = require('html-validator')
// ...
// ...
validator(options)
  .then((result) => {
    if (result.toLowerCase().includes('error')) {
      console.log(`Error on ${url}\n`.error, result)
      callback(Error('Found html error'))
    } else if (result.toLowerCase().includes('warning')) {
      console.log(`Warning on ${url}\n`.error, result)
      callback(Error('Found html warning'))
    } else {
      callback() //OK
    }
  })
  .catch((err) => {
    console.log(err) // Which specific error is thrown when the server is down?
    callback(Error(err))
  })
```

It's hard for me now to check because the W3C server now is running OK :)

**Comment by jfoclpf** [comment]
Now I see, it's on the title :) error 503

**Comment by zrrrzzt** [comment]
For all http statuses except 200 you will get an `Error: Validator returned unexpected statuscode: 503` from the module.

**Comment by jfoclpf** [comment]
Thus, would say that `err.includes("503")` would always work?

```js
const validator = require('html-validator')
// ...
// ...
validator(options)
  .then((result) => {
    // ...
  })
  .catch((err) => {
    if (err.includes("503")) {
      console.log("could not validate this right now, move on")
      callback() // OK
    } else {
      callback(Error(err))
  })
```

**Comment by zrrrzzt** [comment]
The way it returns errors now this approach will catch the 503's.

You can test it by setting `https://httpstatus.allthethings.win/503` as your validator. It's a service I created for returning whatever httpstatus you want :-)

**Comment by jfoclpf** [comment]
Thanks a lot, I used your test url, great service :)
btw, it was supposed to be `err.message.includes('503')`
Thanks again

**Comment by zrrrzzt** [comment]
Happy to help :-)

I'll close this issue now. The new version of the module will be released soon, but it will now be a minor version bump and not major. Thank you for you help and great examples.

**Comment by jfoclpf** [comment]
> For all http statuses except 200 you will get an `Error: Validator returned unexpected statuscode: 503` from the module.

Just FYI, I got today this error, I got a 504 error, that is, not every error gets a 503

```
Error: Error: Error validating html on pages: Error: Validator returned unexpected statuscode: 504
    at /home/jfolpf/autocosts/test/validateHtmlW3C.js:46:19
    at /home/jfolpf/autocosts/node_modules/async/dist/async.js:2960:19
    at wrapper (/home/jfolpf/autocosts/node_modules/async/dist/async.js:273:20)
    at iterateeCallback (/home/jfolpf/autocosts/node_modules/async/dist/async.js:418:21)
    at /home/jfolpf/autocosts/node_modules/async/dist/async.js:326:20
    at /home/jfolpf/autocosts/node_modules/async/dist/async.js:2958:17
    at /home/jfolpf/autocosts/test/validateHtmlW3C.js:108:7
    at wrapper (/home/jfolpf/autocosts/node_modules/async/dist/async.js:273:20)
    at iteratorCallback (/home/jfolpf/autocosts/node_modules/async/dist/async.js:498:17)
    at /home/jfolpf/autocosts/node_modules/async/dist/async.js:326:20

```
