### ISSUE TITLE
node support

### ISSUE THREAD

**Issue by simonihmig** [zrrrzzt/html-validator#87]
Is there a reason this library requires at least node 8.11? A quick glance did not reveal language features that require this. And I quickly ran the tests under node 6 and everything was passing...

This effectively prevents using this in other projects/libraries (e.g. [here](https://github.com/stefanpenner/broccoli-concat-analyser/pull/30)) that still support node 6 (which is still a maintained LTS version), as `npm i` / `yarn` will fail in those cases because of the `engine` requirement (https://github.com/zrrrzzt/html-validator/blob/master/package.json#L13)

I can create a PR to relieve the requirement, if you agree!?

**Comment by zrrrzzt** [comment]
Thank you for your input.

The reason is none other than keeping it simple to maintain for one person. I try to have Node LTS as target for all my modules and with Node 8 async/await is available and that would make this even simpler.

However: at the moment I'm not using async/await and as long as the test passes there's no reason for me to *not* support Node 6.  I'll look into it and if everything works fine I'll change the requirements for the engine :-)

**Comment by simonihmig** [comment]
@zrrrzzt Thank you for the quick response and fix! 👍
